// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBdivLi_pEF0hcH55Qpm_AxSshl3rLh5JQ',
//     appId: '', // TODO: Add your Web App ID from Firebase Console
//     messagingSenderId: '', // TODO: Add your Messaging Sender ID from Firebase Console
//     projectId: 'gigs-a63da',
//     authDomain: 'gigs-a63da.firebaseapp.com',
//     storageBucket: 'gigs-a63da.appspot.com',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBdivLi_pEF0hcH55Qpm_AxSshl3rLh5JQ',
//     appId: '', // TODO: Add your Android App ID from Firebase Console
//     messagingSenderId: '', // TODO: Add your Messaging Sender ID from Firebase Console
//     projectId: 'gigs-a63da',
//     storageBucket: 'gigs-a63da.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBdivLi_pEF0hcH55Qpm_AxSshl3rLh5JQ',
//     appId: '', // TODO: Add your iOS App ID from Firebase Console
//     messagingSenderId: '', // TODO: Add your Messaging Sender ID from Firebase Console
//     projectId: 'gigs-a63da',
//     storageBucket: 'gigs-a63da.appspot.com',
//     iosBundleId: 'com.example.myApp',
//   );
// }
